"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const auth_routes_1 = __importDefault(require("./auth.routes"));
const category_routes_1 = __importDefault(require("./category.routes"));
const program_routes_1 = __importDefault(require("./program.routes"));
const episode_routes_1 = __importDefault(require("./episode.routes"));
const actor_routes_1 = __importDefault(require("./actor.routes"));
const character_routes_1 = __importDefault(require("./character.routes"));
const producer_routes_1 = __importDefault(require("./producer.routes"));
const favorite_routes_1 = __importDefault(require("./favorite.routes"));
const comment_routes_1 = __importDefault(require("./comment.routes"));
const recommendation_routes_1 = __importDefault(require("./recommendation.routes"));
const user_routes_1 = __importDefault(require("./user.routes"));
const router = (0, express_1.Router)();
router.use("/auth", auth_routes_1.default);
router.use("/categories", category_routes_1.default);
router.use("/programs", program_routes_1.default);
router.use("/episodes", episode_routes_1.default);
router.use("/actors", actor_routes_1.default);
router.use("/characters", character_routes_1.default);
router.use("/producers", producer_routes_1.default);
router.use("/favorites", favorite_routes_1.default);
router.use("/comments", comment_routes_1.default);
router.use("/recommendations", recommendation_routes_1.default);
router.use("/users", user_routes_1.default);
exports.default = router;
